export interface GrantSite {
  id: string;
  name: string;
  url: string;
  region: string;
  description: string;
  category: string;
  crawlHint?: string;
  jsHeavy?: boolean; // true = likely blocked/JS-rendered
}

export const KNOWN_GRANT_SITES: GrantSite[] = [
  // ── Australia ──────────────────────────────────────────────────────────────
  {
    id: "business_gov_au",
    name: "Business.gov.au Grants",
    url: "https://business.gov.au/grants-and-programs",
    region: "Australia",
    category: "Business",
    description: "Australian business grants and programs",
    crawlHint: "Extract all grant and program names, funding amounts, eligibility and deadlines",
  },
  {
    id: "grantconnect",
    name: "GrantConnect (Australia)",
    url: "https://www.grants.gov.au/Go/List",
    region: "Australia",
    category: "Government",
    description: "Australian Government grants portal",
    crawlHint: "Extract grant opportunity names, agencies, amounts and closing dates",
  },
  {
    id: "creative_aus",
    name: "Creative Australia Grants",
    url: "https://creative.gov.au/investment-and-development/grants-and-investment/",
    region: "Australia",
    category: "Arts & Culture",
    description: "Arts and cultural funding from the Australian Government",
    crawlHint: "Focus on grant names, amounts, eligibility for artists and arts organisations",
  },
  {
    id: "arc_au",
    name: "Australian Research Council",
    url: "https://www.arc.gov.au/funding-research/funding-schemes",
    region: "Australia",
    category: "Research",
    description: "ARC research funding schemes",
    crawlHint: "Extract research grant scheme names, amounts, eligibility and deadlines",
  },
  {
    id: "nhmrc_au",
    name: "NHMRC Funding (Australia)",
    url: "https://www.nhmrc.gov.au/funding/find-funding/grants",
    region: "Australia",
    category: "Health & Medical",
    description: "National Health and Medical Research Council grants",
    crawlHint: "Extract health and medical research grant names, amounts and deadlines",
  },
  {
    id: "vic_gov",
    name: "Vic Gov Business Grants",
    url: "https://business.vic.gov.au/grants-and-programs",
    region: "Australia",
    category: "Business",
    description: "Victorian Government business grants",
    crawlHint: "Extract grant names, funding amounts, eligibility criteria and application deadlines",
  },
  {
    id: "nsw_gov",
    name: "NSW Government Grants",
    url: "https://www.nsw.gov.au/grants-and-funding",
    region: "Australia",
    category: "Government",
    description: "NSW Government grants and funding programs",
    crawlHint: "Extract all grant names, amounts, eligibility and deadlines",
  },
  // ── United States ──────────────────────────────────────────────────────────
  {
    id: "grants_gov",
    name: "Grants.gov (US Federal)",
    url: "https://www.grants.gov/search-grants",
    region: "United States",
    category: "Government",
    description: "All US federal grant opportunities",
    jsHeavy: true,
    crawlHint: "Extract federal grant names, agencies, CFDA numbers, amounts and deadlines",
  },
  {
    id: "sba_grants",
    name: "SBA Small Business Grants",
    url: "https://www.sba.gov/funding-programs/grants",
    region: "United States",
    category: "Business",
    description: "US Small Business Administration grants",
    crawlHint: "Extract grant program names, eligibility, amounts and how to apply",
  },
  {
    id: "nea_grants",
    name: "National Endowment for the Arts",
    url: "https://www.arts.gov/grants",
    region: "United States",
    category: "Arts & Culture",
    description: "US federal arts grants",
    crawlHint: "Extract arts grant names, amounts, deadlines and eligibility",
  },
  {
    id: "nih_grants",
    name: "NIH Funding Opportunities",
    url: "https://grants.nih.gov/funding/searchguide/index.aspx",
    region: "United States",
    category: "Health & Medical",
    description: "National Institutes of Health research grants",
    jsHeavy: true,
    crawlHint: "Extract NIH grant mechanism names, amounts, deadlines and eligibility",
  },
  // ── United Kingdom ─────────────────────────────────────────────────────────
  {
    id: "ukri",
    name: "UKRI Funding Finder",
    url: "https://www.ukri.org/opportunity/",
    region: "UK",
    category: "Research",
    description: "UK Research and Innovation funding",
    crawlHint: "Extract research funding opportunity names, amounts, deadlines and eligibility",
  },
  {
    id: "innovate_uk",
    name: "Innovate UK Smart Grants",
    url: "https://www.ukri.org/councils/innovate-uk/",
    region: "UK",
    category: "Innovation",
    description: "UK innovation and R&D grants",
    crawlHint: "Extract innovation grant names, funding amounts, eligibility and deadlines",
  },
  {
    id: "arts_council_uk",
    name: "Arts Council England Grants",
    url: "https://www.artscouncil.org.uk/ProjectGrants",
    region: "UK",
    category: "Arts & Culture",
    description: "Arts Council England project grants",
    crawlHint: "Extract arts grant names, amounts, eligibility and deadlines",
  },
  // ── Europe ─────────────────────────────────────────────────────────────────
  {
    id: "eu_funding",
    name: "EU Funding & Tenders Portal",
    url: "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/grant-offers",
    region: "Europe",
    category: "Government",
    description: "European Commission grant opportunities",
    jsHeavy: true,
    crawlHint: "Extract EU grant names, programmes, amounts, deadlines and eligibility",
  },
  {
    id: "horizon_europe",
    name: "Horizon Europe",
    url: "https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en",
    region: "Europe",
    category: "Research",
    description: "EU flagship research and innovation programme",
    crawlHint: "Extract Horizon Europe grant calls, amounts, deadlines and eligibility",
  },
  // ── Global ─────────────────────────────────────────────────────────────────
  {
    id: "candid",
    name: "Candid Foundation Directory",
    url: "https://candid.org/find-funding",
    region: "Global",
    category: "Philanthropy",
    description: "Foundation grants and philanthropy",
    crawlHint: "Extract foundation grant names, amounts, eligibility and deadlines",
  },
  {
    id: "devex",
    name: "Devex Funding",
    url: "https://www.devex.com/funding",
    region: "Global",
    category: "International Development",
    description: "International development funding",
    jsHeavy: true,
    crawlHint: "Extract development grant names, donors, amounts and deadlines",
  },
  {
    id: "open_philanthropy",
    name: "Open Philanthropy Grants",
    url: "https://www.openphilanthropy.org/grants/",
    region: "Global",
    category: "Philanthropy",
    description: "Open Philanthropy grant database",
    crawlHint: "Extract grant names, recipients, amounts and focus areas",
  },
  {
    id: "wellcome_trust",
    name: "Wellcome Trust Funding",
    url: "https://wellcome.org/grant-funding",
    region: "Global",
    category: "Health & Medical",
    description: "Wellcome Trust health research grants",
    crawlHint: "Extract grant scheme names, amounts, eligibility and deadlines",
  },
  {
    id: "gates_foundation",
    name: "Gates Foundation Grants",
    url: "https://www.gatesfoundation.org/about/committed-grants",
    region: "Global",
    category: "Philanthropy",
    description: "Bill & Melinda Gates Foundation grants",
    crawlHint: "Extract grant names, recipients, amounts and focus areas",
  },
  // ── Canada ──────────────────────────────────────────────────────────────────
  {
    id: "sshrc_ca",
    name: "SSHRC (Canada)",
    url: "https://www.sshrc-crsh.gc.ca/funding-financement/programs-programmes-eng.aspx",
    region: "Canada",
    category: "Research",
    description: "Social Sciences and Humanities Research Council funding",
    crawlHint: "Extract research grant names, amounts, eligibility and deadlines",
  },
  {
    id: "nserc_ca",
    name: "NSERC (Canada)",
    url: "https://www.nserc-crsng.gc.ca/Professors-Professeurs/Grants-Subs/index_eng.asp",
    region: "Canada",
    category: "Research",
    description: "Natural Sciences and Engineering Research Council grants",
    crawlHint: "Extract research grant names, amounts, eligibility and deadlines",
  },
  {
    id: "cihr_ca",
    name: "CIHR Funding (Canada)",
    url: "https://cihr-irsc.gc.ca/e/193.html",
    region: "Canada",
    category: "Health & Medical",
    description: "Canadian Institutes of Health Research funding",
    crawlHint: "Extract health research grant names, amounts, eligibility and deadlines",
  },
  {
    id: "innovation_ca",
    name: "Innovation Canada",
    url: "https://innovation.ised-isde.canada.ca/innovation/s/?language=en",
    region: "Canada",
    category: "Business",
    description: "Canadian government business support programs",
    jsHeavy: true,
    crawlHint: "Extract program names, funding amounts, eligibility and deadlines",
  },
  // ── New Zealand ─────────────────────────────────────────────────────────────
  {
    id: "callaghan_nz",
    name: "Callaghan Innovation (NZ)",
    url: "https://www.callaghaninnovation.govt.nz/grants",
    region: "New Zealand",
    category: "Innovation",
    description: "New Zealand R&D and innovation grants",
    crawlHint: "Extract grant names, amounts, eligibility and deadlines",
  },
  {
    id: "creative_nz",
    name: "Creative New Zealand Grants",
    url: "https://www.creativenz.govt.nz/funding-and-support/find-funding",
    region: "New Zealand",
    category: "Arts & Culture",
    description: "Arts and creative sector funding in New Zealand",
    crawlHint: "Extract arts grant names, amounts, eligibility and deadlines",
  },
  {
    id: "mbie_nz",
    name: "MBIE Funding (NZ)",
    url: "https://www.mbie.govt.nz/science-and-technology/science-and-innovation/funding-information-and-opportunities/",
    region: "New Zealand",
    category: "Research",
    description: "Ministry of Business, Innovation and Employment research funding",
    crawlHint: "Extract research funding names, amounts and deadlines",
  },
  // ── United States (additional) ──────────────────────────────────────────────
  {
    id: "nsf_grants",
    name: "NSF Funding Opportunities",
    url: "https://www.nsf.gov/funding/",
    region: "United States",
    category: "Research",
    description: "National Science Foundation funding programs",
    crawlHint: "Extract research grant names, amounts, deadlines and eligibility",
  },
  {
    id: "neh_grants",
    name: "NEH Grants (US Humanities)",
    url: "https://www.neh.gov/grants",
    region: "United States",
    category: "Arts & Culture",
    description: "National Endowment for the Humanities grants",
    crawlHint: "Extract humanities grant names, amounts, deadlines and eligibility",
  },
  {
    id: "usda_grants",
    name: "USDA Grants & Opportunities",
    url: "https://www.usda.gov/topics/farming/grants-and-loans",
    region: "United States",
    category: "Agriculture & Food",
    description: "US Department of Agriculture grants and loans",
    crawlHint: "Extract agriculture grant names, amounts, eligibility and deadlines",
  },
  {
    id: "ed_grants",
    name: "US Dept of Education Grants",
    url: "https://www2.ed.gov/fund/grants-apply.html",
    region: "United States",
    category: "Education & Training",
    description: "US federal education grants",
    crawlHint: "Extract education grant names, amounts, eligibility and deadlines",
  },
  // ── Australia (additional state-level) ──────────────────────────────────────
  {
    id: "qld_gov",
    name: "QLD Government Grants",
    url: "https://www.business.qld.gov.au/starting-business/advice-support/grants",
    region: "Australia",
    category: "Business",
    description: "Queensland Government business grants",
    crawlHint: "Extract grant names, funding amounts, eligibility and deadlines",
  },
  {
    id: "sa_gov",
    name: "SA Government Grants",
    url: "https://www.sa.gov.au/topics/business-and-trade/starting-a-business/grants-and-funding",
    region: "Australia",
    category: "Business",
    description: "South Australia Government grants",
    crawlHint: "Extract grant names, funding amounts, eligibility and deadlines",
  },
  {
    id: "wa_gov",
    name: "WA Government Grants",
    url: "https://www.wa.gov.au/organisation/department-of-local-government-sport-and-cultural-industries/grants-and-funding",
    region: "Australia",
    category: "Business",
    description: "Western Australia Government grants and funding",
    crawlHint: "Extract grant names, funding amounts, eligibility and deadlines",
  },
  {
    id: "tas_gov",
    name: "TAS Government Grants",
    url: "https://www.business.tas.gov.au/grants_and_financial_assistance",
    region: "Australia",
    category: "Business",
    description: "Tasmania Government business grants",
    crawlHint: "Extract grant names, funding amounts, eligibility and deadlines",
  },
  {
    id: "csiro_au",
    name: "CSIRO Programs",
    url: "https://www.csiro.au/en/work-with-us/funding-programs",
    region: "Australia",
    category: "Research",
    description: "CSIRO research and collaboration programs",
    crawlHint: "Extract research program names, amounts and eligibility",
  },
  // ── Europe (additional) ─────────────────────────────────────────────────────
  {
    id: "erc_europe",
    name: "European Research Council",
    url: "https://erc.europa.eu/apply-grant",
    region: "Europe",
    category: "Research",
    description: "ERC frontier research grants",
    crawlHint: "Extract ERC grant scheme names, amounts, deadlines and eligibility",
  },
  {
    id: "erasmus_plus",
    name: "Erasmus+ Programme",
    url: "https://erasmus-plus.ec.europa.eu/opportunities",
    region: "Europe",
    category: "Education & Training",
    description: "EU education and training mobility programme",
    crawlHint: "Extract programme names, amounts, eligibility and deadlines",
  },
  // ── Global (additional) ─────────────────────────────────────────────────────
  {
    id: "ford_foundation",
    name: "Ford Foundation Grants",
    url: "https://www.fordfoundation.org/work/our-grants/",
    region: "Global",
    category: "Philanthropy",
    description: "Ford Foundation social justice grants",
    crawlHint: "Extract grant names, recipients, amounts and focus areas",
  },
  {
    id: "rockefeller_foundation",
    name: "Rockefeller Foundation Grants",
    url: "https://www.rockefellerfoundation.org/grants/",
    region: "Global",
    category: "Philanthropy",
    description: "Rockefeller Foundation grants and programmes",
    crawlHint: "Extract grant names, amounts and focus areas",
  },
  {
    id: "un_sdg_fund",
    name: "UN SDG Fund",
    url: "https://www.sdgfund.org/",
    region: "Global",
    category: "International Development",
    description: "United Nations Sustainable Development Goals Fund",
    crawlHint: "Extract programme names, amounts and focus areas",
  },
  {
    id: "global_fund",
    name: "The Global Fund",
    url: "https://www.theglobalfund.org/en/funding-model/",
    region: "Global",
    category: "Health & Medical",
    description: "Global Fund to fight AIDS, TB and Malaria",
    crawlHint: "Extract funding programme names, amounts and eligibility",
  },
];

export const GRANT_SITE_CATEGORIES = [
  "All",
  "Business",
  "Research",
  "Health & Medical",
  "Arts & Culture",
  "Innovation",
  "Government",
  "Philanthropy",
  "International Development",
  "Education & Training",
  "Agriculture & Food",
];

export const GRANT_SITE_REGIONS = [
  "All",
  "Australia",
  "United States",
  "UK",
  "Europe",
  "Canada",
  "New Zealand",
  "Global",
];
