export interface GrantSite {
  id: string;
  name: string;
  url: string;
  region: string;
  description: string;
  category: string;
  crawlHint?: string;
  jsHeavy?: boolean; // true = likely blocked/JS-rendered
}

export const KNOWN_GRANT_SITES: GrantSite[] = [
  // ── Australia ──────────────────────────────────────────────────────────────
  {
    id: "business_gov_au",
    name: "Business.gov.au Grants",
    url: "https://business.gov.au/grants-and-programs",
    region: "Australia",
    category: "Business",
    description: "Australian business grants and programs",
    crawlHint: "Extract all grant and program names, funding amounts, eligibility and deadlines",
  },
  {
    id: "grantconnect",
    name: "GrantConnect (Australia)",
    url: "https://www.grants.gov.au/Go/List",
    region: "Australia",
    category: "Government",
    description: "Australian Government grants portal",
    crawlHint: "Extract grant opportunity names, agencies, amounts and closing dates",
  },
  {
    id: "creative_aus",
    name: "Creative Australia Grants",
    url: "https://creative.gov.au/investment-and-development/grants-and-investment/",
    region: "Australia",
    category: "Arts & Culture",
    description: "Arts and cultural funding from the Australian Government",
    crawlHint: "Focus on grant names, amounts, eligibility for artists and arts organisations",
  },
  {
    id: "arc_au",
    name: "Australian Research Council",
    url: "https://www.arc.gov.au/funding-research/funding-schemes",
    region: "Australia",
    category: "Research",
    description: "ARC research funding schemes",
    crawlHint: "Extract research grant scheme names, amounts, eligibility and deadlines",
  },
  {
    id: "nhmrc_au",
    name: "NHMRC Funding (Australia)",
    url: "https://www.nhmrc.gov.au/funding/find-funding/grants",
    region: "Australia",
    category: "Health & Medical",
    description: "National Health and Medical Research Council grants",
    crawlHint: "Extract health and medical research grant names, amounts and deadlines",
  },
  {
    id: "vic_gov",
    name: "Vic Gov Business Grants",
    url: "https://business.vic.gov.au/grants-and-programs",
    region: "Australia",
    category: "Business",
    description: "Victorian Government business grants",
    crawlHint: "Extract grant names, funding amounts, eligibility criteria and application deadlines",
  },
  {
    id: "nsw_gov",
    name: "NSW Government Grants",
    url: "https://www.nsw.gov.au/grants-and-funding",
    region: "Australia",
    category: "Government",
    description: "NSW Government grants and funding programs",
    crawlHint: "Extract all grant names, amounts, eligibility and deadlines",
  },
  // ── United States ──────────────────────────────────────────────────────────
  {
    id: "grants_gov",
    name: "Grants.gov (US Federal)",
    url: "https://www.grants.gov/search-grants",
    region: "United States",
    category: "Government",
    description: "All US federal grant opportunities",
    jsHeavy: true,
    crawlHint: "Extract federal grant names, agencies, CFDA numbers, amounts and deadlines",
  },
  {
    id: "sba_grants",
    name: "SBA Small Business Grants",
    url: "https://www.sba.gov/funding-programs/grants",
    region: "United States",
    category: "Business",
    description: "US Small Business Administration grants",
    crawlHint: "Extract grant program names, eligibility, amounts and how to apply",
  },
  {
    id: "nea_grants",
    name: "National Endowment for the Arts",
    url: "https://www.arts.gov/grants",
    region: "United States",
    category: "Arts & Culture",
    description: "US federal arts grants",
    crawlHint: "Extract arts grant names, amounts, deadlines and eligibility",
  },
  {
    id: "nih_grants",
    name: "NIH Funding Opportunities",
    url: "https://grants.nih.gov/funding/searchguide/index.aspx",
    region: "United States",
    category: "Health & Medical",
    description: "National Institutes of Health research grants",
    jsHeavy: true,
    crawlHint: "Extract NIH grant mechanism names, amounts, deadlines and eligibility",
  },
  // ── United Kingdom ─────────────────────────────────────────────────────────
  {
    id: "ukri",
    name: "UKRI Funding Finder",
    url: "https://www.ukri.org/opportunity/",
    region: "UK",
    category: "Research",
    description: "UK Research and Innovation funding",
    crawlHint: "Extract research funding opportunity names, amounts, deadlines and eligibility",
  },
  {
    id: "innovate_uk",
    name: "Innovate UK Smart Grants",
    url: "https://www.ukri.org/councils/innovate-uk/",
    region: "UK",
    category: "Innovation",
    description: "UK innovation and R&D grants",
    crawlHint: "Extract innovation grant names, funding amounts, eligibility and deadlines",
  },
  {
    id: "arts_council_uk",
    name: "Arts Council England Grants",
    url: "https://www.artscouncil.org.uk/ProjectGrants",
    region: "UK",
    category: "Arts & Culture",
    description: "Arts Council England project grants",
    crawlHint: "Extract arts grant names, amounts, eligibility and deadlines",
  },
  // ── Europe ─────────────────────────────────────────────────────────────────
  {
    id: "eu_funding",
    name: "EU Funding & Tenders Portal",
    url: "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/grant-offers",
    region: "Europe",
    category: "Government",
    description: "European Commission grant opportunities",
    jsHeavy: true,
    crawlHint: "Extract EU grant names, programmes, amounts, deadlines and eligibility",
  },
  {
    id: "horizon_europe",
    name: "Horizon Europe",
    url: "https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en",
    region: "Europe",
    category: "Research",
    description: "EU flagship research and innovation programme",
    crawlHint: "Extract Horizon Europe grant calls, amounts, deadlines and eligibility",
  },
  // ── Global ─────────────────────────────────────────────────────────────────
  {
    id: "candid",
    name: "Candid Foundation Directory",
    url: "https://candid.org/find-funding",
    region: "Global",
    category: "Philanthropy",
    description: "Foundation grants and philanthropy",
    crawlHint: "Extract foundation grant names, amounts, eligibility and deadlines",
  },
  {
    id: "devex",
    name: "Devex Funding",
    url: "https://www.devex.com/funding",
    region: "Global",
    category: "International Development",
    description: "International development funding",
    jsHeavy: true,
    crawlHint: "Extract development grant names, donors, amounts and deadlines",
  },
  {
    id: "open_philanthropy",
    name: "Open Philanthropy Grants",
    url: "https://www.openphilanthropy.org/grants/",
    region: "Global",
    category: "Philanthropy",
    description: "Open Philanthropy grant database",
    crawlHint: "Extract grant names, recipients, amounts and focus areas",
  },
  {
    id: "wellcome_trust",
    name: "Wellcome Trust Funding",
    url: "https://wellcome.org/grant-funding",
    region: "Global",
    category: "Health & Medical",
    description: "Wellcome Trust health research grants",
    crawlHint: "Extract grant scheme names, amounts, eligibility and deadlines",
  },
  {
    id: "gates_foundation",
    name: "Gates Foundation Grants",
    url: "https://www.gatesfoundation.org/about/committed-grants",
    region: "Global",
    category: "Philanthropy",
    description: "Bill & Melinda Gates Foundation grants",
    crawlHint: "Extract grant names, recipients, amounts and focus areas",
  },
];

export const GRANT_SITE_CATEGORIES = [
  "All",
  "Business",
  "Research",
  "Health & Medical",
  "Arts & Culture",
  "Innovation",
  "Government",
  "Philanthropy",
  "International Development",
];

export const GRANT_SITE_REGIONS = [
  "All",
  "Australia",
  "United States",
  "UK",
  "Europe",
  "Global",
];
